<%-- The Java code in this JSP file runs on the server when the user navigates
     to the homepage. This allows us to insert the Blobstore upload URL into the
     form without building the HTML using print statements in a servlet. --%>
<%@ page import="com.google.appengine.api.blobstore.BlobstoreService" %>
<%@ page import="com.google.appengine.api.blobstore.BlobstoreServiceFactory" %>
<% BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();
   String uploadUrl = blobstoreService.createUploadUrl("/formhandler"); %>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>St. Andrews AME STEM Camp</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
  </head>
  <body onload="ListComments()">
    <div id="content">
      <div id="commentCont"></div>
      <!-- <form method="POST" enctype="multipart/form-data" action="/data"> -->
    <form method="POST" enctype="multipart/form-data" action="<%= uploadUrl %>">
        <p>Add comment:</p> 
        <textarea type="text" name="comment"></textarea>
        <br/>
        <p>Upload an image:</p>
        <input type="file" name="image">
        <br/><br/>
        <button>Submit</button>
    </form>
      <h1>St. Andrews AME Stem Camp!</h1>
      <p>Bringing education and knowledge where it is needed most</p>
      <p>Click <a href="/data">here</a> to view content generated by a servlet.</p>
      <a href="images/STEMCamp2019.png"><img src="images/STEMCamp2019.png"/></a>
      <p>Random message:</p>
      <button onclick="addRandomGreeting()">Hello</button>
      <div id="greeting-container"></div>
    </div>
  </body>
</html>
